// Generated by CoffeeScript 1.4.0
var Kappa, Player, Shot, Tsuyama, py,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

enchant();

py = 0;

Tsuyama = (function(_super) {

  __extends(Tsuyama, _super);

  function Tsuyama() {
    Tsuyama.__super__.constructor.call(this, 320, 320);
    this.fps = 30;
    Tsuyama.game = this;
    this.preload("kappa.png", "combat.png", "bg.png", "fb.png");
    this.time = 0;
    py = 0;
    this.onload = function() {
      var player;
      this.background = new Sprite(320, 320);
      this.background.image = this.assets['bg.png'];
      this.rootScene.addChild(this.background);
      player = new Player(0, 0);
      this.rootScene.addChild(player);
      this.rootScene.ontouchstart = function(e) {
        return py = e.y;
      };
      return this.onenterframe = function() {
        this.time++;
        if (this.time % 70 === 0) {
          return this.rootScene.addChild(new Kappa(288, Math.random() * 288));
        }
      };
    };
    this.start();
  }

  return Tsuyama;

})(Game);

Player = (function(_super) {

  __extends(Player, _super);

  function Player(x, y) {
    Player.__super__.constructor.call(this, 32, 32);
    this.x = x;
    this.y = y;
    this.game = Tsuyama.game;
    this.image = this.game.assets['combat.png'];
    this.frameList = [1, 1, 1, 2, 2, 2];
    this.frameIndex = 0;
  }

  Player.prototype.onenterframe = function() {
    return this.y = py;
  };

  return Player;

})(Sprite);

Shot = (function(_super) {

  __extends(Shot, _super);

  function Shot() {
    Shot.__super__.constructor.call(this, 32, 32);
    this.x = player.x;
    this.y = player.y;
    this.game = Tsuyama.game;
    this.image = this.game.assets['fb.png'];
  }

  Shot.prototype.onenterframe = function() {
    return this.x += 2;
  };

  return Shot;

})(Sprite);

Kappa = (function(_super) {

  __extends(Kappa, _super);

  function Kappa(x, y) {
    Kappa.__super__.constructor.call(this, 32, 32);
    this.x = x;
    this.y = y;
    this.game = Tsuyama.game;
    this.image = this.game.assets['kappa.png'];
    this.frameIndex = 0;
    this.frameList = [1, 1, 1, 2, 2, 2];
  }

  Kappa.prototype.onenterframe = function() {
    this.x--;
    this.frameIndex++;
    this.frameIndex %= this.frameList.length;
    this.frame = this.frameList[this.frameIndex];
    if (this.x === -32) {
      return this.parentNode.removeChild(this);
    }
  };

  return Kappa;

})(Sprite);

window.onload = function() {
  return new Tsuyama();
};
